### ISSUE TITLE
Edits do not trigger EditorJS’s onChange()

### ISSUE THREAD

**Issue by hagemann** [editor-js/raw#12]
After page load, initial edits in the textarea do not trigger the EditorJS `onChange` listener unless other blocks are modified first.

**Comment by Darkinsideus** [comment]
Confirm. Until you make changes in other blocks, it doesn't save changes in raw block.

**Comment by VitaliyDemchuk** [comment]
This is a critical bug. When will the fix be?

**Comment by m-alzam** [comment]
> After page load, initial edits in the textarea do not trigger the EditorJS `onChange` listener unless other blocks are modified first.

I can't reproduce this issue - works for me.

**Comment by hagemann** [comment]
@m-alzam Without touching anything and typing in the textbox the first thing?

**Comment by m-alzam** [comment]
> @m-alzam Without touching anything and typing in the textbox the first thing?

Hmm, confirmed. The `onChange` listener is not triggered. It maybe related to #843

**Comment by neSpecc** [comment]
Should be fixed in editorjs 2.19
