### ISSUE TITLE
No HTML tags in returned code

### ISSUE THREAD

**Issue by m-alzam** [editor-js/raw#7]
raw plugin version: `2.1.1` (lastest)
editor.js version: `2.17.0` (lastest)

The raw plugin is not returning the HTML tags in the returned code after calling the `save()` function of the editor. For example, the following code:

```html
<b>CODE<b>
```
returns
```json
{
    "time" : 1584382663969,
    "blocks" : [
        {
            "type" : "raw",
            "data" : {
                "html" : "CODE"
            }
        }
    ],
    "version" : "2.17.0"
}
```

This issue maybe related to the editor's [sanitizer](https://editorjs.io/sanitizer).

**Comment by m-alzam** [comment]
This [line](https://github.com/codex-team/editor.js/blob/ac93017c706f091fd3014c3edb248db4e03f55dd/src/components/modules/saver.ts#L43) sanitizes the data.

**Comment by donmorton** [comment]
@m-alzam did you find a work around for this?

**Comment by m-alzam** [comment]
@donmorton fixed in pull request

**Comment by Darkinsideus** [comment]
Добрый день. Когда будет обновление плагина?

**Comment by VitaliyDemchuk** [comment]
Update plugin version, please!

**Comment by m-alzam** [comment]
@VitaliyDemchuk @Darkinsideus the plugin version is updated in the PR; a new version will be released when it's merged.

**Comment by gohabereg** [comment]
Hi @m-alzam @Darkinsideus @VitaliyDemchuk 
The new version is published. Thanks for @m-alzam !

**Comment by VitaliyDemchuk** [comment]
@m-alzam @gohabereg thanks.

**Comment by nihartrivedi810** [comment]
Hi @m-alzam @gohabereg @donmorton @VitaliyDemchuk ,

I am still facing this issue in version 2.1.2.

All the tags are being stripped except the tags related to toolbar options shown below:

![image](https://user-images.githubusercontent.com/5328845/87181590-341db580-c300-11ea-80ce-6c74d8431e23.png)
